[prototype_nodes]
lab-node-01 ansible_host=192.0.2.11 pcie_slot=0000:04:00.0
lab-node-02 ansible_host=192.0.2.12 pcie_slot=0000:04:00.0
lab-node-03 ansible_host=192.0.2.13 pcie_slot=0000:06:00.0

[build_nodes]
build-01 ansible_host=192.0.2.21

[all:vars]
ansible_user=devops
ansible_python_interpreter=/usr/bin/python3
